"""init db

Revision ID: 0ab061671773
Revises: 
Create Date: 2023-09-25 19:56:05.484734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab061671773'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company'))
    )
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process'))
    )
    op.create_table('company_process',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_process_company_id_company')),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], name=op.f('fk_company_process_process_id_process'))
    )
    op.execute("""
            INSERT INTO company (id, name) VALUES (1, 'criaway');
        """)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_process')
    op.drop_table('process')
    op.drop_table('company')
    # ### end Alembic commands ###
